In [5]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
graph = tf.Graph()
batch_size = 1
emb_shape = []
sess = tf.Session(graph=graph)

def line(): print('-'*20)

def show(t):
    t = sess.run(t)
    print(t)

def tile(v, m):
    vv = tf.tile(v, m)
    vv = tf.reshape(vv, [bs,bs,-1])
    return vv

ethalons = np.asarray([[1],[2],[3]])
request  = np.asarray([[-1],[2.51],[3]])

bs = ethalons.shape[0]

with graph.as_default():
    e0 = tf.constant(ethalons, dtype=tf.float16)
    e1 = tf.constant(request,  dtype=tf.float16)
    e0 = tile(e0, [bs,1])
    e1 = tile(e1, [1,bs])

    e0 = tf.reshape(e0, [-1])
    e1 = tf.reshape(e1, [-1])
    
    d = tf.sqrt((e1 - e0)**2)
    d = tf.reshape(d, [bs, bs, -1])
    d = tf.reduce_sum(d, axis=2)
    r = tf.argmin(d, 1)
    l = np.linspace(0,bs-1,bs)
    q = tf.cast(tf.equal(r,l), dtype=tf.float32)
    acc = tf.reduce_mean(q)
    sess.run(tf.global_variables_initializer())
    
    
#show(d1)
#show(r1)
#print('-'*20)
show(e0)
show(e1)
line()
show(d)
show(r)
show(q)
show(acc)


[ 1.  2.  3.  1.  2.  3.  1.  2.  3.]
[-1.         -1.         -1.          2.50976562  2.50976562  2.50976562
  3.          3.          3.        ]
--------------------
[[ 2.          3.          4.        ]
 [ 1.50976562  0.50976562  0.49023438]
 [ 2.          1.          0.        ]]
[0 2 2]
[ 1.  0.  1.]
0.666667
